ALTER TABLE pessoa
RENAME TO TB_PERSON;

ALTER TABLE TB_PERSON
CHANGE COLUMN nome FULL_NAME varchar(100) NOT NULL;

ALTER TABLE TB_PERSON
CHANGE COLUMN cpf DOCUMENT_NUMBER varchar(14) NOT NULL;

ALTER TABLE TB_PERSON
CHANGE COLUMN telefone TELEPHONE_NUMBER varchar(18);

ALTER TABLE TB_PERSON
CHANGE COLUMN id ID_PERSON int unsigned auto_increment;

ALTER TABLE TB_PERSON
ADD COLUMN INCLUSION_DATE DATE NOT NULL;

ALTER TABLE TB_PERSON
ADD CONSTRAINT unique_document_number UNIQUE (DOCUMENT_NUMBER);

ALTER TABLE TB_PERSON
CHANGE COLUMN name EMAIL varchar(100);

ALTER TABLE TB_PERSON
DROP FOREIGN KEY TB_PERSON_ibfk_1;

ALTER TABLE TB_PERSON
DROP COLUMN id_endereco;

ALTER TABLE TB_PERSON
DROP COLUMN full_name;

INSERT INTO TB_PERSON (DOCUMENT_NUMBER, INCLUSION_DATE) VALUES ('032103210332', now());
INSERT INTO TB_PERSON (DOCUMENT_NUMBER, INCLUSION_DATE) VALUES ('032103210333', now());








