create table TB_JURIDICAL_PERSON (

  ID_JURIDICAL_PERSON int unsigned,
  DATE_OPENING date not null,
  FANTASY_NAME varchar (100),
  SOCIAL_REASON varchar (100) not null,
  PRIMARY KEY(ID_JURIDICAL_PERSON),
  CONSTRAINT FK_PERSON_TB_JURIRICAL_PERSON FOREIGN KEY (ID_JURIDICAL_PERSON) REFERENCES TB_PERSON(ID_PERSON)

)engine = INNODB default  charset = utf8;

INSERT INTO TB_JURIDICAL_PERSON (ID_JURIDICAL_PERSON, DATE_OPENING, FANTASY_NAME, SOCIAL_REASON)
VALUES ('1', now(), 'DIRCE COIFFEUR', 'DIRCE COIFFEUR LTDA');