create table TB_JURIDICAL_PERSON (

  ID_JURIDICAL_PERSON int unsigned,
  ID_GROUP_PERSON int unsigned not null,
  DATE_OPENING date not null,
  FANTASY_NAME varchar (100),
  SOCIAL_REASON varchar (100) not null,
  CONSTRAINT FK_GROUP_PERSON_TB_JURIDICAL_PERSON FOREIGN KEY (ID_GROUP_PERSON) REFERENCES TB_GROUP_PERSON(ID_GROUP_PERSON),
  CONSTRAINT FK_PERSON_TB_JURIDICAL_PERSON FOREIGN KEY (ID_JURIDICAL_PERSON) REFERENCES TB_PERSON(ID_PERSON),
  PRIMARY KEY(ID_JURIDICAL_PERSON)

)engine = INNODB default  charset = utf8;

INSERT INTO TB_JURIDICAL_PERSON (ID_JURIDICAL_PERSON, DATE_OPENING, FANTASY_NAME, SOCIAL_REASON, ID_GROUP_PERSON)
VALUES ('1', now(), 'DIRCE COIFFEUR', 'DIRCE COIFFEUR LTDA', '1');

INSERT INTO TB_JURIDICAL_PERSON (ID_JURIDICAL_PERSON, DATE_OPENING, FANTASY_NAME, SOCIAL_REASON, ID_GROUP_PERSON)
VALUES ('2', now(), 'DIRCE COIFFEUR', 'DIRCE COIFFEUR LTDA', '2');