CREATE TABLE TB_EMPLOYEE (

  ID_EMPLOYEE int unsigned not null,
  ID_JURIDICAL_PERSON int unsigned not null,
  ID_ROLE int unsigned not null,
  ADMISSION_DATE DATE not null,
  WITHDRAW_DATE DATE,
  CONSTRAINT FK_ROLE_TB_EMPLOYEE FOREIGN KEY (ID_ROLE) REFERENCES TB_ROLE(ID_ROLE),
  CONSTRAINT FK_FISIC_PERSON_TB_EMPLOYEE FOREIGN KEY (ID_EMPLOYEE) REFERENCES TB_FISIC_PERSON(ID_FISIC_PERSON),
  CONSTRAINT FK_JURIDICAL_PERSON_TB_EMPLOYEE FOREIGN KEY (ID_JURIDICAL_PERSON) REFERENCES TB_JURIDICAL_PERSON(ID_JURIDICAL_PERSON),
  PRIMARY KEY (ID_EMPLOYEE)

)engine = INNODB default  charset = utf8;



